services:
  frontend:
    image: ghcr.io/krisvan/pickleball-scheduler/frontend:latest
    container_name: frontend
    build:
      context: ../pickletime-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ../pickletime-frontend/.env
    command: ["npm", "run", "preview"]

  backend:
    image: ghcr.io/krisvan/pickleball-scheduler/backend:latest
    container_name: backend
    build:
      context: ../pickletime-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../pickletime-backend/.env
    depends_on:
      - postgres
    command: ["npm", "run", "start"]

  postgres:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - ../pickletime-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
