services:
  frontend:
    image: ghcr.io/pickle-time/pickletime-frontend:latest
    container_name: frontend
    build:
      context: ../pickletime-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ../pickletime-frontend/.env
    command: ["npm", "run", "preview"]

  backend:
    image: ghcr.io/pickle-time/pickletime-backend:latest
    container_name: backend
    build:
      context: ../pickletime-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../pickletime-backend/.env
    depends_on:
      - postgres
    command: [ "sh", "-c", "npx prisma migrate dev && npm run seed && npm run start" ]

  certbot: # Runs once to generate the SSL certificate
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: [
      "certonly", "--webroot",
      "--webroot-path=/var/www/certbot",
      "--email", "kristophervan1999@gmail.com",
      "--agree-tos",
      "--no-eff-email",
      "--staging", # Remove this line for production
      "-d", "pickletime.duckdns.org"
    ]
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.certbot.conf:/etc/nginx/conf.d/default.conf # Swap with default.production.conf after generating the certificate
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot

  postgres:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - ../pickletime-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
