# Development Docker Compose file for PickleTime. Builds images from local 
# directories and uses local .env files.
services:
  frontend:
    container_name: frontend
    build:
      context: ../pickletime-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ../pickletime-frontend/.env
    command: ["npm", "run", "preview"]

  backend:
    container_name: backend
    build:
      context: ../pickletime-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../pickletime-backend/.env
    depends_on:
      - postgres
    command: [ "sh", "-c", "npx prisma migrate dev && npm run seed && npm run start" ]

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - ../pickletime-backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
