server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container_name

      - source_labels: [__meta_docker_container_image]
        target_label: container_image

      - source_labels: [__meta_docker_container_labels_com_docker_compose_service]
        target_label: compose_service
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{container_name="backend"}'
          stages:
            - json:
                expressions:
                  level: level
                  ts: time
                  statusCode: res.statusCode
                  method: req.method
                  url: req.url
                  hostname: req.hostname
                  reqId: reqId
                  responseTime: responseTime
                  msg: msg
                  remoteAddress: remoteAddress
                  
            - timestamp:
                source: ts
                format: UnixMillis
            - labels:
                level:
                method:

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log
