# docker network create public
# docker network create internal
# docker network create monitoring

services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    # ports:
    #   - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki 
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /tmp:/tmp
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
      - internal

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
    env_file:
      - ../.env
    # ports:
      # - "3000:3000"
    networks:
      - public
      - monitoring
volumes:
  grafana_data:
  loki_data:

networks:
  public:
    external: true
  internal:
    external: true
  monitoring:
    external: true