name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/opc/projects/pickletime/pickletime-infra
            git pull origin main

            # Ensure required Docker networks exist
            docker network create public || true
            docker network create internal || true
            docker network create monitoring || true
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            cd /monitoring
            docker compose -f docker-compose.monitoring.yml pull
            docker compose -f docker-compose.monitoring.yml up -d --remove-orphans
